name: 'gem-audit'
description: 'Audit Gemfile.lock for vulnerable gem versions and insecure sources'
author: '7a6163'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  version:
    description: 'gem-audit version to use'
    required: false
    default: 'latest'
  severity:
    description: 'Minimum severity level to report (none, low, medium, high, critical)'
    required: false
  strict:
    description: 'Treat parse/load warnings as errors (exit code 2)'
    required: false
    default: 'false'
  max-db-age:
    description: 'Maximum advisory database age in days before warning'
    required: false
  fail-on-stale:
    description: 'Exit with code 3 if the advisory database is stale'
    required: false
    default: 'false'
  gemfile-lock:
    description: 'Path to the Gemfile.lock file'
    required: false
    default: 'Gemfile.lock'
  ignore:
    description: 'Space-separated advisory IDs to ignore'
    required: false
  format:
    description: 'Output format: text or json'
    required: false
    default: 'text'
  output:
    description: 'Write output to a file instead of stdout'
    required: false
  working-directory:
    description: 'Project directory to audit'
    required: false
    default: '.'
  quiet:
    description: 'Suppress output'
    required: false
    default: 'false'
  verbose:
    description: 'Show detailed advisory descriptions'
    required: false
    default: 'false'
  reviewdog:
    description: 'Enable reviewdog to post inline PR comments for findings'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for reviewdog API access'
    required: false
    default: '${{ github.token }}'
  reviewdog-reporter:
    description: 'reviewdog reporter (github-pr-review, github-pr-check, github-check)'
    required: false
    default: 'github-pr-review'
  reviewdog-filter-mode:
    description: 'reviewdog filter mode (nofilter shows all findings regardless of diff)'
    required: false
    default: 'nofilter'

outputs:
  exit-code:
    description: 'Exit code from gem-audit (0=clean, 1=vulnerable, 2=error, 3=stale)'
    value: ${{ steps.audit.outputs.exit-code }}

runs:
  using: 'composite'
  steps:
    - name: Detect platform
      id: platform
      shell: bash
      run: |
        case "${{ runner.os }}-${{ runner.arch }}" in
          Linux-X64)   target="x86_64-unknown-linux-gnu" ;;
          Linux-ARM64) target="aarch64-unknown-linux-gnu" ;;
          macOS-X64)   target="x86_64-apple-darwin" ;;
          macOS-ARM64) target="aarch64-apple-darwin" ;;
          Windows-X64) target="x86_64-pc-windows-msvc" ;;
          *) echo "::error::Unsupported platform: ${{ runner.os }}-${{ runner.arch }}" && exit 1 ;;
        esac
        echo "target=$target" >> "$GITHUB_OUTPUT"

    - name: Download gem-audit
      id: download
      shell: bash
      run: |
        version="${{ inputs.version }}"
        target="${{ steps.platform.outputs.target }}"

        if [ "$version" = "latest" ]; then
          download_url=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/7a6163/gem-audit/releases/latest" \
            | grep "browser_download_url.*${target}" \
            | head -1 \
            | cut -d '"' -f 4)
        else
          download_url="https://github.com/7a6163/gem-audit/releases/download/v${version}/gem-audit-${target}.tar.gz"
        fi

        if [ -z "$download_url" ]; then
          echo "::error::Could not find gem-audit release for target ${target}"
          exit 1
        fi

        echo "Downloading gem-audit from ${download_url}"
        curl -sL "$download_url" -o gem-audit.tar.gz
        tar -xzf gem-audit.tar.gz
        chmod +x gem-audit
        echo "bin=${{ github.workspace }}/gem-audit" >> "$GITHUB_OUTPUT"

    - name: Run gem-audit
      id: audit
      shell: bash
      run: |
        args=("check")
        args+=("${{ inputs.working-directory }}")
        args+=("--gemfile-lock" "${{ inputs.gemfile-lock }}")
        args+=("--format" "${{ inputs.format }}")

        if [ "${{ inputs.quiet }}" = "true" ]; then
          args+=("--quiet")
        fi

        if [ "${{ inputs.verbose }}" = "true" ]; then
          args+=("--verbose")
        fi

        if [ -n "${{ inputs.severity }}" ]; then
          args+=("--severity" "${{ inputs.severity }}")
        fi

        if [ "${{ inputs.strict }}" = "true" ]; then
          args+=("--strict")
        fi

        if [ -n "${{ inputs.max-db-age }}" ]; then
          args+=("--max-db-age" "${{ inputs.max-db-age }}")
        fi

        if [ "${{ inputs.fail-on-stale }}" = "true" ]; then
          args+=("--fail-on-stale")
        fi

        if [ -n "${{ inputs.ignore }}" ]; then
          args+=("--ignore" ${{ inputs.ignore }})
        fi

        if [ -n "${{ inputs.output }}" ]; then
          args+=("--output" "${{ inputs.output }}")
        fi

        set +e
        ${{ steps.download.outputs.bin }} "${args[@]}"
        code=$?
        set -e

        echo "exit-code=$code" >> "$GITHUB_OUTPUT"
        exit $code

    - name: Install reviewdog
      if: inputs.reviewdog == 'true' && (success() || failure())
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

    - name: Report findings with reviewdog
      if: inputs.reviewdog == 'true' && (success() || failure())
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      run: |
        lockfile="${{ inputs.working-directory }}/${{ inputs.gemfile-lock }}"

        args=("check")
        args+=("${{ inputs.working-directory }}")
        args+=("--gemfile-lock" "${{ inputs.gemfile-lock }}")
        args+=("--format" "json")

        if [ -n "${{ inputs.severity }}" ]; then
          args+=("--severity" "${{ inputs.severity }}")
        fi

        if [ "${{ inputs.strict }}" = "true" ]; then
          args+=("--strict")
        fi

        if [ -n "${{ inputs.max-db-age }}" ]; then
          args+=("--max-db-age" "${{ inputs.max-db-age }}")
        fi

        if [ -n "${{ inputs.ignore }}" ]; then
          args+=("--ignore" ${{ inputs.ignore }})
        fi

        set +e
        json_output=$(${{ steps.download.outputs.bin }} "${args[@]}" 2>/dev/null)
        set -e

        if [ -z "$json_output" ]; then
          echo "No findings to report."
          exit 0
        fi

        echo "$json_output" | jq -c '
          .unpatched_gems // [] | .[] |
          {
            name: .name,
            version: .version,
            advisories: (.advisories // [])
          }
        ' | while IFS= read -r gem; do
          gem_name=$(echo "$gem" | jq -r '.name')
          gem_version=$(echo "$gem" | jq -r '.version')

          line=$(grep -Fn "    ${gem_name} (${gem_version})" "$lockfile" | head -1 | cut -d: -f1 || true)

          echo "$gem" | jq -c '.advisories[]' | while IFS= read -r advisory; do
            id=$(echo "$advisory" | jq -r '.id // empty')
            title=$(echo "$advisory" | jq -r '.title // "Unknown vulnerability"')
            url=$(echo "$advisory" | jq -r '.url // empty')
            criticality=$(echo "$advisory" | jq -r '.criticality // "unknown"' | tr '[:upper:]' '[:lower:]')

            case "$criticality" in
              critical|high) severity="ERROR" ;;
              medium)        severity="WARNING" ;;
              *)             severity="INFO" ;;
            esac

            message="${id}: ${title}"

            if [ -n "$line" ]; then
              location=$(jq -n -c --arg path "$lockfile" --argjson line "$line" \
                '{path: $path, range: {start: {line: $line, column: 1}}}')
            else
              location=$(jq -n -c --arg path "$lockfile" '{path: $path}')
            fi

            if [ -n "$id" ] && [ -n "$url" ]; then
              code_obj=$(jq -n -c --arg value "$id" --arg url "$url" '{value: $value, url: $url}')
            elif [ -n "$id" ]; then
              code_obj=$(jq -n -c --arg value "$id" '{value: $value}')
            else
              code_obj="{}"
            fi

            jq -n -c \
              --arg message "$message" \
              --arg severity "$severity" \
              --argjson location "$location" \
              --argjson code "$code_obj" \
              '{message: $message, location: $location, severity: $severity, code: $code}'
          done
        done | reviewdog \
          -f=rdjsonl \
          -name=gem-audit \
          -reporter="${{ inputs.reviewdog-reporter }}" \
          -filter-mode="${{ inputs.reviewdog-filter-mode }}" \
          -fail-level=none \
          -level=warning

        # Also report insecure sources
        echo "$json_output" | jq -c '
          .insecure_sources // [] | .[]
        ' | while IFS= read -r source; do
          source_url=$(echo "$source" | jq -r '.url // .source // empty')
          if [ -z "$source_url" ]; then
            source_url=$(echo "$source" | jq -r '. | if type == "string" then . else empty end')
          fi

          if [ -z "$source_url" ]; then
            continue
          fi

          line=$(grep -Fn "$source_url" "$lockfile" | head -1 | cut -d: -f1 || true)

          message="Insecure source: ${source_url}"

          if [ -n "$line" ]; then
            location=$(jq -n -c --arg path "$lockfile" --argjson line "$line" \
              '{path: $path, range: {start: {line: $line, column: 1}}}')
          else
            location=$(jq -n -c --arg path "$lockfile" '{path: $path}')
          fi

          jq -n -c \
            --arg message "$message" \
            --argjson location "$location" \
            '{message: $message, location: $location, severity: "WARNING"}'
        done | reviewdog \
          -f=rdjsonl \
          -name=gem-audit \
          -reporter="${{ inputs.reviewdog-reporter }}" \
          -filter-mode="${{ inputs.reviewdog-filter-mode }}" \
          -fail-level=none \
          -level=warning
